version: "3"

services:
  asteroids_swag:
    container_name: asteroids_swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=asteroids-ba.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=993de60e-d20f-47ca-8464-018ce7a8a380
      - STAGING=false
    volumes:
      - swag_config:/config
      - ./ops/swag/nginx.conf:/config/nginx/site-confs/default.conf
      - /data/nginx/cache
    ports:
      - 6123:443
    restart: unless-stopped

  asteroids_client:
    container_name: asteroids_client
    replicas: 2
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped

  asteroids_actor_system:
    container_name: asteroids_actor_system
    build:
      context: .
      dockerfile: ./actorSystem/Dockerfile
    restart: unless-stopped

  asteroids_signalr:
    container_name: asteroids_signalr
    build:
      context: .
      dockerfile: ./signalR/Dockerfile
    restart: unless-stopped

  asteroids_grafana:
    image: grafana/grafana:latest
    container_name: asteroids_grafana
    user: 1000:1000
    ports:
      - 6001:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    restart: unless-stopped

  asteroids_prometheus:
    image: prom/prometheus:latest
    container_name: asteroids_prometheus
    ports:
      - 6002:9090
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # depends_on:
    #   - asteroids_actor_system
    restart: unless-stopped

  asteroids_loki:
    image: grafana/loki:latest
    container_name: asteroids_loki
    ports:
      - 6003:3100
    restart: unless-stopped

  asteroids_zipkin:
    image: openzipkin/zipkin:latest
    container_name: asteroids_zipkin
    ports:
      - 6004:9411
    restart: unless-stopped

  asteroids_otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: asteroids_otel-collector
    volumes:
      - ./ops/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1887:1888 # pprof extension
      - 8887:8888 # Prometheus metrics exposed by the Collector
      - 8886:8889 # Prometheus exporter metrics
      - 13132:13133 # health_check extension
      - 4316:4317 # OTLP gRPC receiver
      - 4319:4318 # OTLP http receiver
      - 55678:55679 # zpages extension
    restart: unless-stopped

volumes:
  grafana_data:
  prometheus_data:
  swag_config:
