version: "3"

services:
  editor:
    container_name: asteroids_editor
    build:
      context: .
    user: developer
    privileged: true
    volumes:
      - developer_home:/home/developer
      - ../:/app/
      - $HOME/.ssh:/home/developer/.ssh
      - $HOME/.gnupg:/home/developer/.gnupg
      - ./.bashrc:/home/developer/.bashrc
      - ./.bash-git-prompt:/home/developer/.bash-git-prompt
    environment:
      - TZ=America/Denver
      - PYTHONPATH=/app/api/
    working_dir: /app
    command: tail -f /dev/null

  client:
    container_name: asteroids_client
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    env_file:
      - .env
    command: >
      sh -c "
        cd client
        npm i
        npm run dev
      "
    ports:
      - 8080:8080

  api:
    container_name: asteroids_api
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    command: >
      sh -c "
        cd api
        dotnet watch run
      "
    environment:
      - DOTNET_WATCH_AUTO_RELOAD=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - ASPNETCORE_ENVIRONMENT=Development
  
  raft-gateway:
    container_name: asteroids_raft_gateway
    build:
      context: ../raft
      dockerfile: Raft.GateWay/Dockerfile
    environment:
      - NODE_ADDRESSES=http://raft-node-1:8080,http://raft-node-2:8080,http://raft-node-3:8080
      - NODE_IDS=node-1,node-2,node-3

  raft-node-1:
    container_name: asteroids_node_1
    image: raft-node:latest
    build:
      context: ../raft
      dockerfile: Raft.Node/Dockerfile
    environment:
      - NODE_ID=asteroids_node_1
      - PEER_ADDRESSES=http://raft-node-2:8080,http://raft-node-3:8080
      - PEER_IDS=asteroids_node_2,asteroids_node_3

  
  raft-node-2:
    container_name: asteroids_node_2
    image: raft-node:latest
    build:
      context: ../raft
      dockerfile: Raft.Node/Dockerfile
    environment:
      - NODE_ID=asteroids_node_2
      - PEER_ADDRESSES=http://raft-node-1:8080,http://raft-node-3:8080
      - PEER_IDS=asteroids_node_1,asteroids_node_3

  raft-node-3:
    container_name: asteroids_node_3
    image: raft-node:latest
    environment:
      - NODE_ID=asteroids_node_3
      - PEER_ADDRESSES=http://raft-node-1:8080,http://raft-node-2:8080
      - PEER_IDS=asteroids_node_1,asteroids_node_2

volumes:
  developer_home:
