version: "3"

services:
  editor:
    container_name: asteroids_editor
    build:
      context: .
    user: developer
    privileged: true
    volumes:
      - developer_home:/home/developer
      - ../:/app/
      - $HOME/.ssh:/home/developer/.ssh
      - $HOME/.gnupg:/home/developer/.gnupg
      - ./.bashrc:/home/developer/.bashrc
      - ./.bash-git-prompt:/home/developer/.bash-git-prompt
    environment:
      - TZ=America/Denver
    working_dir: /app
    command: tail -f /dev/null

  client:
    container_name: asteroids_client
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    env_file:
      - .env
    command: >
      sh -c "
        cd client
        npm i
        npm run dev
      "
    ports:
      - 8080:8080

  actor-system:
    container_name: asteroids_actor_system
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    command: >
      sh -c "
        cd actorSystem
        dotnet watch run
      "
    environment:
      - DOTNET_WATCH_AUTO_RELOAD=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - ASPNETCORE_ENVIRONMENT=Development
      - SIGNALR_URL=http://asteroids_signalr:8080/ws
  
  raft-gateway:
    container_name: asteroids_raft_gateway
    build:
      context: ../raft
      dockerfile: Raft.GateWay/Dockerfile
    environment:
      - NODE_ADDRESSES=http://raft-node-1:8080,http://raft-node-2:8080,http://raft-node-3:8080
      - NODE_IDS=asteroids_node_1,asteroids_node_2,asteroids_node_3

  raft-node-1:
    container_name: asteroids_node_1
    image: raft-node:latest
    build:
      context: ../raft
      dockerfile: Raft.Node/Dockerfile
    environment:
      - NODE_ID=asteroids_node_1
      - PEER_ADDRESSES=http://raft-node-2:8080,http://raft-node-3:8080
      - PEER_IDS=asteroids_node_2,asteroids_node_3

  
  raft-node-2:
    container_name: asteroids_node_2
    image: raft-node:latest
    build:
      context: ../raft
      dockerfile: Raft.Node/Dockerfile
    environment:
      - NODE_ID=asteroids_node_2
      - PEER_ADDRESSES=http://raft-node-1:8080,http://raft-node-3:8080
      - PEER_IDS=asteroids_node_1,asteroids_node_3

  raft-node-3:
    container_name: asteroids_node_3
    image: raft-node:latest
    environment:
      - NODE_ID=asteroids_node_3
      - PEER_ADDRESSES=http://raft-node-1:8080,http://raft-node-2:8080
      - PEER_IDS=asteroids_node_1,asteroids_node_2

  asteroids_signalr:
    container_name: asteroids_signalr
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    command: >
      sh -c "
        cd signalR
        dotnet watch run
      "
    environment:
      - DOTNET_WATCH_AUTO_RELOAD=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - ASPNETCORE_ENVIRONMENT=Development

  asteroids_grafana:
    image: grafana/grafana:latest
    container_name: asteroids_grafana
    user: 1000:1000
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../dev-ops/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml

  asteroids_prometheus:
    image: prom/prometheus:latest
    container_name: asteroids_prometheus
    ports:
      - 9090:9090
    volumes:
      - ../dev-ops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # depends_on:
    #   - asteroids_actor_system

  asteroids_loki:
    image: grafana/loki:latest
    container_name: asteroids_loki
    ports:
      - 3100:3100

  asteroids_zipkin:
    image: openzipkin/zipkin:latest
    container_name: asteroids_zipkin
    ports:
      - 9411:9411

  asteroids_otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: asteroids_otel-collector
    volumes:
      - ../dev-ops/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

volumes:
  developer_home:
  grafana_data:
  prometheus_data:
