{
 "title": "Asteroids",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "LobbyCount_Number_of_lobbies", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Joining Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JoiningLobbies_Number_of_Lobbies_in_the_Joining_State",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playing Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PlayingLobbies_Number_of_Lobbies_in_the_Playing_State",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asteroid System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | __error__=``"
    }
   ]
  },
  {
   "title": "Game Over Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "GameOverLobbies_Number_of_Lobbies_in_the_GameOver_State",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stopped Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "StoppedLobbies_Number_of_Lobbies_in_the_Stopped_State",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Countdown Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CountdownLobbies_Number_of_Lobbies_in_the_Countdown_State",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PlayerCount_Number_of_Players_in_Lobbies",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shots Fired",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalShotsFired_Total_shots_fired_by_all_players",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}